#!/usr/bin/env sh
set -eu

go test ./...
go vet ./...
./scripts/verify-probe-artifacts.sh
./scripts/verify-tx-workload-artifacts.sh

GOOS=linux GOARCH=amd64 go test -exec=/usr/bin/true ./...
GOOS=darwin GOARCH=amd64 go test -exec=/usr/bin/true ./...
GOOS=darwin GOARCH=arm64 go test -exec=/usr/bin/true ./...
GOOS=freebsd GOARCH=amd64 go test -exec=/usr/bin/true ./...
GOOS=windows GOARCH=amd64 go test -exec=/usr/bin/true ./...
